#!/bin/bash

# Script de démonstration FIT CLI
# Ce script montre les fonctionnalités principales du CLI

echo "🎯 Démonstration FIT CLI"
echo "========================"

# Vérifier que le CLI est installé
if [ ! -f "./fit" ]; then
    echo "❌ Fichier 'fit' non trouvé. Veuillez installer FIT CLI d'abord."
    exit 1
fi

# Rendre le script exécutable
chmod +x ./fit

echo ""
echo "📋 1. Aide et version"
echo "-------------------"
./fit --help
echo ""
./fit version

echo ""
echo "🔍 2. Statut de connexion"
echo "------------------------"
./fit status

echo ""
echo "🔐 3. Authentification (simulation)"
echo "-----------------------------------"
echo "Note: Ces commandes nécessitent une connexion à FIT"
echo ""
echo "# Connexion en tant que patient:"
echo "./fit login --username 'patient@example.com' --password 'password' --role 'patient'"
echo ""
echo "# Connexion en tant que clinicien:"
echo "./fit login --username 'doctor@example.com' --password 'password' --role 'clinician'"
echo ""
echo "# Connexion en tant qu'agent IA:"
echo "./fit login --username 'ai@example.com' --password 'password' --role 'ai'"

echo ""
echo "👤 4. Commandes Patient (Joueur)"
echo "--------------------------------"
echo "# Déclarer des symptômes:"
echo "./fit patient symptoms 'douleur ischio jambe gauche' --severity 'moderate' --duration 'depuis 3 jours'"
echo ""
echo "# Demander un rendez-vous:"
echo "./fit patient appointment request --date '2025-09-20' --reason 'contrôle PCMA'"
echo ""
echo "# Lister les rendez-vous:"
echo "./fit patient appointment list"
echo ""
echo "# Consulter le suivi:"
echo "./fit patient followup"
echo ""
echo "# Demander une seconde opinion:"
echo "./fit patient second-opinion request"

echo ""
echo "🩺 5. Commandes Clinicien"
echo "------------------------"
echo "# Commencer une visite:"
echo "./fit clinician visit start --player 10"
echo ""
echo "# Ajouter un diagnostic:"
echo "./fit clinician diagnosis add --player 10 --condition 'Entorse cheville gauche'"
echo ""
echo "# Créer un plan de soins:"
echo "./fit clinician careplan create --player 10 --treatment 'Physiothérapie 2 semaines'"
echo ""
echo "# Évaluer l'aptitude PCMA:"
echo "./fit clinician pcma evaluate --player 10"
echo ""
echo "# Signaler une blessure:"
echo "./fit clinician injury report --player 10 --type 'Ischio' --severity 'Grade 2'"
echo ""
echo "# Créer un rendez-vous (Secrétaire):"
echo "./fit clinician secretary create --player 10 --date '2025-09-21' --reason 'Bilan blessure'"

echo ""
echo "🤖 6. Commandes Agent IA"
echo "------------------------"
echo "# Générer un résumé de visite:"
echo "./fit agent summarize visit --player 10"
echo ""
echo "# Surveiller la récupération:"
echo "./fit agent monitor recovery --player 10"
echo ""
echo "# Détecter les écarts de soins:"
echo "./fit agent monitor caregap --player 10"
echo ""
echo "# Envoyer un message:"
echo "./fit agent message --to 'player10' --text 'Reprise progressive demain, 20 min vélo'"
echo ""
echo "# Rechercher des preuves médicales:"
echo "./fit agent evidence --condition 'entorse cheville' --player 10"

echo ""
echo "🔄 7. Workflow Complet - Exemple"
echo "--------------------------------"
echo "# Workflow: Blessure → Consultation → Plan de soins → Suivi IA"
echo ""
echo "# 1. Patient déclare des symptômes"
echo "./fit patient symptoms 'douleur cheville gauche' --severity 'severe' --duration '1 jour'"
echo ""
echo "# 2. Patient demande un rendez-vous"
echo "./fit patient appointment request --date '2025-09-20' --reason 'blessure cheville'"
echo ""
echo "# 3. Clinicien commence la visite"
echo "./fit clinician visit start --player 10"
echo ""
echo "# 4. Clinicien pose un diagnostic"
echo "./fit clinician diagnosis add --player 10 --condition 'Entorse cheville gauche Grade 2'"
echo ""
echo "# 5. Clinicien crée un plan de soins"
echo "./fit clinician careplan create --player 10 --treatment 'Physiothérapie 2 semaines, repos relatif'"
echo ""
echo "# 6. IA génère un résumé"
echo "./fit agent summarize visit --player 10"
echo ""
echo "# 7. IA surveille la récupération"
echo "./fit agent monitor recovery --player 10"
echo ""
echo "# 8. IA envoie un message de suivi"
echo "./fit agent message --to 'player10' --text 'Séance de physiothérapie demain à 10h'"

echo ""
echo "🧪 8. Tests et Validation"
echo "-------------------------"
echo "# Exécuter les tests d'installation:"
echo "python test-installation.py"
echo ""
echo "# Exécuter les tests unitaires:"
echo "python -m pytest tests/"
echo ""
echo "# Exécuter les tests d'intégration:"
echo "python -m pytest tests/test_integration.py -v"

echo ""
echo "🐳 9. Déploiement Docker"
echo "-----------------------"
echo "# Construire l'image:"
echo "docker build -t fit-cli ."
echo ""
echo "# Exécuter le CLI:"
echo "docker run -it --rm fit-cli --help"
echo ""
echo "# Déployer avec Docker Compose:"
echo "docker-compose up -d"
echo "docker-compose exec fit-cli --help"

echo ""
echo "📚 10. Documentation"
echo "--------------------"
echo "# Guide d'utilisation:"
echo "cat USAGE.md"
echo ""
echo "# Architecture:"
echo "cat ARCHITECTURE.md"
echo ""
echo "# Configuration:"
echo "cat .fitconfig"

echo ""
echo "✅ Démonstration terminée!"
echo ""
echo "🚀 Pour commencer:"
echo "1. Installez les dépendances: pip install -r requirements.txt"
echo "2. Testez l'installation: python test-installation.py"
echo "3. Connectez-vous à FIT: ./fit login --username 'user@example.com' --password 'password' --role 'patient'"
echo "4. Explorez les commandes: ./fit --help"
echo ""
echo "📖 Pour plus d'informations, consultez USAGE.md et ARCHITECTURE.md"
