# -*- coding: utf-8 -*-
import sys
path = 'resources/views/pcma/create.blade.php'
content = open(path, encoding='utf-8').read()

replacements = [
    ("<h1> Rapport d'Évaluation PCMA</h1>",
     "<h1> {{ __('pcma.report_title') }}</h1>", 1),
    ("<p>Date: ${new Date().toLocaleDateString('fr-FR')}</p>",
     "<p>{{ __('pcma.report_date_label') }} ${new Date().toLocaleDateString('en-GB')}</p>", 1),
    ('<h3>👤 Informations du Patient</h3>',
     "<h3>{{ __('pcma.report_patient_info_title') }}</h3>", 1),
    ('<label>Athlète:</label>',
     "<label>{{ __('pcma.report_athlete_label') }}</label>", 1),
    ("'Non spécifié'", "@json(__('pcma.report_not_specified'))", 16),
    ("<label>Type d'évaluation:</label>",
     "<label>{{ __('pcma.report_assessment_type_label') }}</label>", 1),
    ("<label>Date d'évaluation:</label>",
     "<label>{{ __('pcma.report_assessment_date_label') }}</label>", 1),
    ('<h3> Signes Vitaux</h3>',
     "<h3> {{ __('pcma.report_vital_signs_title') }}</h3>", 1),
    ('<label>Tension Artérielle:</label>',
     "<label>{{ __('pcma.report_blood_pressure_label') }}</label>", 1),
    ('<label>Fréquence Cardiaque:</label>',
     "<label>{{ __('pcma.report_heart_rate_label') }}</label>", 1),
    ('<label>Température:</label>',
     "<label>{{ __('pcma.report_temperature_label') }}</label>", 1),
    ('<h3> Antécédents Médicaux</h3>',
     "<h3> {{ __('pcma.report_medical_history_title') }}</h3>", 1),
    ('<label>Antécédents Cardio-vasculaires:</label>',
     "<label>{{ __('pcma.report_cardiovascular_history_label') }}</label>", 1),
    ("${formDataObj.cardiovascular_history || 'Aucun'}",
     "${formDataObj.cardiovascular_history || @json(__('pcma.report_none'))}", 1),
    ('<label>Antécédents Chirurgicaux:</label>',
     "<label>{{ __('pcma.report_surgical_history_label') }}</label>", 1),
    ("${formDataObj.surgical_history || 'Aucun'}",
     "${formDataObj.surgical_history || @json(__('pcma.report_none'))}", 1),
    ('<label>Médicaments Actuels:</label>',
     "<label>{{ __('pcma.report_medications_label') }}</label>", 1),
    ("${formDataObj.medications || 'Aucun'}",
     "${formDataObj.medications || @json(__('pcma.report_none'))}", 1),
    ('<label>Allergies:</label>',
     "<label>{{ __('pcma.report_allergies_label') }}</label>", 1),
    ("${formDataObj.allergies || 'Aucune'}",
     "${formDataObj.allergies || @json(__('pcma.report_none_f'))}", 1),
    ('<h3> Examen Physique</h3>',
     "<h3> {{ __('pcma.report_physical_exam_title') }}</h3>", 1),
    ('<label>Apparence Générale:</label>',
     "<label>{{ __('pcma.report_general_appearance_label') }}</label>", 1),
    ('<label>Examen Cutané:</label>',
     "<label>{{ __('pcma.report_skin_exam_label') }}</label>", 1),
    ('<h3>❤️ Évaluation Cardiovasculaire</h3>',
     "<h3>{{ __('pcma.cardio_assessment_title') }}</h3>", 1),
    ('<label>Rythme Cardiaque:</label>',
     "<label>{{ __('pcma.report_cardiac_rhythm_label') }}</label>", 1),
    ('<label>Souffle Cardiaque:</label>',
     "<label>{{ __('pcma.report_heart_murmur_label') }}</label>", 1),
    ('<h3>🧠 Évaluation Neurologique</h3>',
     "<h3>{{ __('pcma.neuro_assessment_title') }}</h3>", 1),
    ('<label>Niveau de Conscience:</label>',
     "<label>{{ __('pcma.report_consciousness_label') }}</label>", 1),
    ('<label>Nerfs Crâniens:</label>',
     "<label>{{ __('pcma.report_cranial_nerves_label') }}</label>", 1),
    ('<h3>💪 Évaluation Musculo-squelettique</h3>',
     "<h3>{{ __('pcma.msk_assessment_title') }}</h3>", 1),
    ('<label>Mobilité Articulaire:</label>',
     "<label>{{ __('pcma.report_joint_mobility_label') }}</label>", 1),
    ('<label>Force Musculaire:</label>',
     "<label>{{ __('pcma.report_muscle_strength_label') }}</label>", 1),
    ('<h3>🏆 Conformité FIFA</h3>',
     "<h3>{{ __('pcma.fifa_compliance_title') }}</h3>", 1),
    ('<label>ID FIFA:</label>',
     "<label>{{ __('pcma.report_fifa_id_label') }}</label>", 1),
    ('<label>Nom de la compétition:</label>',
     "<label>{{ __('pcma.report_competition_name_label') }}</label>", 1),
    ('<label>Conforme aux standards FIFA:</label>',
     "<label>{{ __('pcma.report_fifa_compliant_label') }}</label>", 1),
    ("${formDataObj.fifa_compliant ? 'Oui' : 'Non'}",
     "${formDataObj.fifa_compliant ? @json(__('pcma.report_yes')) : @json(__('pcma.report_no'))}", 1),
    ('<h3> Notes</h3>',
     "<h3> {{ __('pcma.report_notes_title') }}</h3>", 1),
    ("${formDataObj.notes || 'Aucune note'}",
     "${formDataObj.notes || @json(__('pcma.report_no_notes'))}", 1),
    ('<h3> Signature Médicale</h3>',
     "<h3> {{ __('pcma.report_signature_title') }}</h3>", 2),
    ('<label>Signé par:</label>',
     "<label>{{ __('pcma.report_signed_by_label') }}</label>", 1),
    ('<label>Numéro de licence:</label>',
     "<label>{{ __('pcma.report_license_number_label') }}</label>", 1),
    ('<label>Date de signature:</label>',
     "<label>{{ __('pcma.report_signature_date_label') }}</label>", 1),
    ("${new Date(window.signedPCMAData.signedAt).toLocaleString('fr-FR')}",
     "${new Date(window.signedPCMAData.signedAt).toLocaleString('en-GB')}", 1),
    ('<label>Adresse IP:</label>',
     "<label>{{ __('pcma.report_ip_address_label') }}</label>", 1),
    ('<label>Statut de fitness:</label>',
     "<label>{{ __('pcma.report_fitness_status_label') }}</label>", 1),
    ('<label>Signature:</label>',
     "<label>{{ __('pcma.report_signature_label') }}</label>", 1),
    ('alt="Signature médicale"',
     "alt=\"{{ __('pcma.report_signature_alt') }}\"", 1),
    ('<label>Déclaration légale:</label>',
     "<label>{{ __('pcma.report_legal_declaration_label') }}</label>", 1),
    ('✓ Confirmée par le médecin signataire',
     "{{ __('pcma.report_legal_confirmed') }}", 1),
    ('<label>Validation:</label>',
     "<label>{{ __('pcma.report_validation_label') }}</label>", 1),
    ('✓ Document médical validé et signé',
     "{{ __('pcma.report_validated') }}", 1),
    ('⚠️ Signature médicale non effectuée',
     "{{ __('pcma.report_signature_missing') }}", 1),
    ('⚠️ Déclaration légale non confirmée',
     "{{ __('pcma.report_legal_not_confirmed') }}", 1),
    ('⚠️ Document non validé',
     "{{ __('pcma.report_document_not_validated') }}", 1),
    ('                        🖨️ Imprimer ce rapport\n',
     "                        {{ __('pcma.report_print_button') }}\n", 1),
]

for old, new, expected in replacements:
    actual = content.count(old)
    if actual != expected:
        print(f"MISMATCH expected={expected} actual={actual} for: {old[:120]!r}")
        sys.exit(1)

for old, new, expected in replacements:
    if expected == 0:
        continue
    content = content.replace(old, new, expected)

open(path, 'w', encoding='utf-8').write(content)
print("BATCH16 OK")
