<div class="fi-u17"><h3>Lecture du radius distal · U‑17</h3><p class="fi-notice fi-amber">Le grade décrit la maturité osseuse. Il ne permet pas d’affirmer un âge réel, une fraude ou une inéligibilité. Le protocole masculin ne doit pas être transposé aux joueuses.</p>
<label>Population concernée<select name="age[population]" id="fi-population"><option value="unspecified" @selected(($age['population']??'unspecified')==='unspecified')>Non documentée · aucune interprétation d’âge</option><option value="male" @selected(($age['population']??'')==='male')>Population masculine · protocole applicable à vérifier</option><option value="female" @selected(($age['population']??'')==='female')>Population féminine · protocole masculin non applicable</option></select></label>
<label>Grade radiologique retenu<select name="age[grade]" id="fi-grade"><option value="">Indéterminé / non applicable</option>@foreach([1=>'I · Absence de fusion',2=>'II · Début de fusion',3=>'III · Fusion inférieure à 50 %',4=>'IV · Fusion supérieure à 50 %',5=>'V · Cartilage résiduel inférieur à 5 mm',6=>'VI · Fusion complète'] as $value=>$label)<option value="{{ $value }}" @selected(($age['grade']??null)==$value)>{{ $label }}</option>@endforeach</select></label>
<p class="fi-hint" id="fi-grade-notice">Sélectionnez les coupes justificatives dans le lecteur. Aucun âge chiffré n’est calculé.</p>
<details><summary>Seconde lecture / désaccord</summary><div class="fi-form"><label>Grade du second lecteur<select name="age[second_grade]" id="fi-second-grade"><option value="">Pas de seconde lecture documentée</option>@for($g=1;$g<=6;$g++)<option value="{{ $g }}" @selected(($age['second_grade']??null)==$g)>Grade {{ $g }}</option>@endfor</select></label><label>Second lecteur<input name="age[second_reader]" value="{{ $age['second_reader']??'' }}" maxlength="180"></label><label>Référence du compte rendu de seconde lecture<input name="age[second_source]" value="{{ $age['second_source']??'' }}" maxlength="500"></label><label>Gestion d’un désaccord éventuel<textarea name="age[disagreement_note]" rows="2" maxlength="2000">{{ $age['disagreement_note']??'' }}</textarea></label></div></details>
<details><summary>Compétition & contrôle documentaire</summary><div class="fi-form"><label>Compétition / édition<input name="age[competition]" value="{{ $age['competition']??'' }}" maxlength="180"></label><label>Référence et version du règlement<input name="age[regulation]" value="{{ $age['regulation']??'' }}" maxlength="500" placeholder="Document, article et édition"></label><label>Date de naissance minimale autorisée<input type="date" name="age[cutoff_birth_date]" value="{{ $age['cutoff_birth_date']??'' }}"></label><p class="fi-hint">Seuil tiré du règlement de cette compétition, sans exclusion automatique selon l’âge du jour.</p>
<div class="fi-evidence"><strong>Pièces effectivement relues</strong><p class="fi-hint">Renseignez les dates présentes sur les pièces sources. Une discordance sera signalée.</p>@for($i=0;$i<3;$i++)<div class="fi-evidence-row"><label>Source<input name="age[evidence][{{ $i }}][source]" value="{{ $age['evidence'][$i]['source']??'' }}" placeholder="Ex. état civil" maxlength="180"></label><label>Référence<input name="age[evidence][{{ $i }}][reference]" value="{{ $age['evidence'][$i]['reference']??'' }}" maxlength="500"></label><label>Date de naissance sur la pièce<input type="date" name="age[evidence][{{ $i }}][birth_date]" value="{{ $age['evidence'][$i]['birth_date']??'' }}"></label></div>@endfor</div>
</div></details>
<label>Contexte clinique utile à l’interprétation<textarea name="age[context]" rows="2" maxlength="3000" placeholder="Antécédents du poignet ou facteurs de maturation documentés">{{ $age['context']??'' }}</textarea></label>
<input type="hidden" name="age[consent]" value="0"><label class="fi-check"><input type="checkbox" name="age[consent]" value="1" @checked($age['consent']??false)> Information et consentement documentés pour ce contrôle, avec le représentant légal lorsque nécessaire.</label>
<div class="fi-hint">Références : <a href="https://pubmed.ncbi.nlm.nih.gov/17021001/" target="_blank" rel="noopener noreferrer">Classification IRM masculine</a> · <a href="https://pubmed.ncbi.nlm.nih.gov/25880786/" target="_blank" rel="noopener noreferrer">Limites dans la population féminine</a></div>
</div>
