<?php

// Versionner toute modification des paramètres : un résultat garde sa version de calcul.
return [
    'version' => '1.0.0',
    'positions' => [
        'LCB' => 'central', 'RCB' => 'central', 'CB' => 'central',
        'LB' => 'lateral', 'RB' => 'lateral',
        'CDM' => 'defensive_midfield', 'DM' => 'defensive_midfield',
        'LCM' => 'central_midfield', 'RCM' => 'central_midfield', 'CM' => 'central_midfield',
        'CAM' => 'attacking_midfield', 'RCAM' => 'attacking_midfield', 'LCAM' => 'attacking_midfield', 'AM' => 'attacking_midfield',
        'LAM' => 'winger', 'RAM' => 'winger', 'LW' => 'winger', 'RW' => 'winger',
        'CF' => 'striker', 'ST' => 'striker', 'GK' => 'goalkeeper',
    ],
    // Aucun repli des gardiens vers les joueurs de champ.
    'reference_fallback' => [
        'central' => ['lateral', 'field'], 'lateral' => ['central', 'field'],
        'defensive_midfield' => ['central_midfield', 'field'],
        'central_midfield' => ['defensive_midfield', 'field'],
        'attacking_midfield' => ['winger', 'field'],
        'winger' => ['attacking_midfield', 'field'],
        'striker' => ['attacking_midfield', 'field'],
        'goalkeeper' => [],
    ],
    'min_reference_minutes' => 270,
    'min_reference_players' => 30,
    'half_life_matches' => 8,
    'minute_weight_denominator' => 60,
    'rate_prior_attempts' => 15,
    'keeper_save_prior_attempts' => 40,
    'z_cap' => 3,
    'mad_scale' => 1.4826,
    'mad_floor' => 0.05,
    'score_center' => 50,
    'score_scale' => 15,
    'tau_variance_floor' => 0.0001,
    'interval_multiplier_80' => 1.28,
    'minimum_reliability_display' => 30,
    'reliability_levels' => ['medium' => 40, 'solid' => 70],
    'weights' => [
        'central' => [5, 25, 10, 30, 25, 5],
        'lateral' => [15, 20, 20, 15, 20, 10],
        'defensive_midfield' => [5, 30, 15, 20, 25, 5],
        'central_midfield' => [15, 30, 20, 15, 15, 5],
        'attacking_midfield' => [30, 25, 25, 5, 10, 5],
        'winger' => [30, 10, 30, 10, 10, 10],
        'striker' => [45, 10, 10, 20, 5, 10],
        'goalkeeper' => [40, 20, 25, 15],
    ],
    'dimensions' => [
        'field' => [
            'finition_creation' => ['goals', 'assists', 'shots_on_target', 'key_passes'],
            'construction' => ['passes', 'pass_rate', 'long_pass_rate'],
            'progression_dribbles' => ['dribbles', 'dribble_rate', 'crosses', 'cross_rate'],
            'duels' => ['tackles', 'tackle_rate', 'ground_duel_rate', 'aerial_duel_rate'],
            'recuperation' => ['interceptions', 'recoveries'],
            'discipline' => ['fouls', 'yellow_cards', 'red_cards', 'mistakes_chances', 'mistakes_goals', 'penalties_conceded', 'balls_lost'],
        ],
        'goalkeeper' => [
            'arrets_buts_evites' => ['save_rate', 'goals_prevented'],
            'gestion_surface' => ['high_claim_rate', 'sweeper_rate'],
            'jeu_au_pied' => ['pass_rate', 'long_pass_rate', 'passes'],
            'securite' => ['mistakes_chances', 'mistakes_goals', 'penalties_conceded', 'balls_lost'],
        ],
    ],
    // Une réussite et son volume proviennent des mêmes actions : leur groupe ne vaut qu'une voix.
    'redundancy_groups' => [
        ['passes', 'pass_rate'], ['dribbles', 'dribble_rate'], ['crosses', 'cross_rate'],
        ['tackles', 'tackle_rate'],
    ],
    'direction' => [
        'fouls' => -1, 'yellow_cards' => -1, 'red_cards' => -1,
        'mistakes_chances' => -1, 'mistakes_goals' => -1,
        'penalties_conceded' => -1, 'balls_lost' => -1,
    ],
    'indicators' => [
        'goals' => ['type' => 'count', 'field' => 'goals_scored', 'average' => 'goals'],
        'assists' => ['type' => 'count', 'field' => 'assists_provided', 'average' => 'assists'],
        'shots_on_target' => ['type' => 'count', 'field' => 'shots_on_target', 'average' => 'shots_on_target'],
        'key_passes' => ['type' => 'count', 'field' => 'key_passes', 'average' => 'key_passes'],
        'passes' => ['type' => 'count', 'field' => 'passes_total', 'average' => 'passes'],
        'dribbles' => ['type' => 'count', 'field' => 'dribbles_attempted', 'average' => 'dribbles'],
        'crosses' => ['type' => 'count', 'field' => 'crosses_total', 'average' => 'crosses'],
        'tackles' => ['type' => 'count', 'field' => 'tackles_total', 'average' => 'tackles'],
        'interceptions' => ['type' => 'count', 'field' => 'interceptions', 'average' => 'interceptions'],
        'recoveries' => ['type' => 'count', 'field' => 'recoveries', 'average' => 'loose_ball_recoveries'],
        'fouls' => ['type' => 'count', 'field' => 'fouls_committed', 'average' => 'fouls_committed'],
        'yellow_cards' => ['type' => 'count', 'field' => 'yellow_cards', 'average' => 'yellow_cards'],
        'red_cards' => ['type' => 'count', 'field' => 'red_cards', 'average' => 'red_cards'],
        'mistakes_chances' => ['type' => 'count', 'field' => 'mistakes_leading_to_chances', 'average' => 'mistakes_leading_to_chances'],
        'mistakes_goals' => ['type' => 'count', 'field' => 'mistakes_leading_to_goals', 'average' => 'mistakes_leading_to_goals'],
        'penalties_conceded' => ['type' => 'count', 'field' => 'penalties_conceded', 'average' => 'penalties_conceded'],
        'balls_lost' => ['type' => 'count', 'field' => 'times_dispossessed', 'average' => 'balls_lost'],
        'pass_rate' => ['type' => 'rate', 'attempt' => 'passes_total', 'success' => 'passes_completed', 'average_attempt' => 'passes', 'average_rate' => 'passes_accuracy'],
        'long_pass_rate' => ['type' => 'rate', 'attempt' => 'long_passes', 'success' => 'long_passes_completed', 'average_attempt' => 'long_passes', 'average_success' => 'long_passes_accurate'],
        'dribble_rate' => ['type' => 'rate', 'attempt' => 'dribbles_attempted', 'success' => 'dribbles_completed', 'average_attempt' => 'dribbles', 'average_rate' => 'dribbles_successful'],
        'cross_rate' => ['type' => 'rate', 'attempt' => 'crosses_total', 'success' => 'crosses_completed', 'average_attempt' => 'crosses', 'average_rate' => 'crosses_accurate'],
        'tackle_rate' => ['type' => 'rate', 'attempt' => 'tackles_total', 'success' => 'tackles_won', 'average_attempt' => 'tackles', 'average_rate' => 'tackles_successful'],
        'ground_duel_rate' => ['type' => 'rate', 'attempt' => 'ground_duels_total', 'success' => 'ground_duels_won', 'average_attempt' => 'challenges', 'average_rate' => 'challenges_won'],
        'aerial_duel_rate' => ['type' => 'rate', 'attempt' => 'aerial_duels_total', 'success' => 'aerial_duels_won', 'average_attempt' => 'aerial_challenges', 'average_rate' => 'aerial_challenges_won'],
        'save_rate' => ['type' => 'rate', 'attempt' => 'shots_on_target_against', 'success' => 'saves', 'average_attempt' => 'shots_on_target_against', 'average_rate' => 'saves_pct'],
        'high_claim_rate' => ['type' => 'rate', 'attempt' => 'high_claims_attempted', 'success' => 'high_claims', 'average_attempt' => 'high_claims_attempted', 'average_rate' => 'high_claims_pct'],
        'sweeper_rate' => ['type' => 'rate', 'attempt' => 'sweeper_actions_attempted', 'success' => 'sweeper_actions', 'average_attempt' => 'sweeper_actions_attempted', 'average_rate' => 'sweeper_actions_pct'],
        'goals_prevented' => ['type' => 'prevented', 'field' => 'goals_prevented', 'expected' => 'post_shot_xg', 'conceded' => 'goals_conceded'],
    ],
];
