-- Extraction des données d'apprentissage du modèle de sélection du cockpit entraîneur.
-- Lecture seule. Usage : psql "$DATABASE" -v out=/chemin/dossier -f scripts/coach-cockpit/export_training_data.sql
\set participations :out '/participations.csv'
\set team_matches :out '/team_matches.csv'
\set role_history :out '/role_history.csv'

-- Participations (feuilles de match effectives) + statistiques détaillées + événements
COPY (SELECT mp.player_id, mp.team_id, mp.match_id, m.matchday, (m.home_club_id = mp.team_id) AS home, CASE WHEN m.home_club_id = mp.team_id THEN m.away_club_id ELSE m.home_club_id END AS opp_id, pc.family, mp.detailed_position, mp.minute_out - mp.minute_in AS mins, mp.is_starter, s.match_rating AS rating, coalesce(s.expected_goals,0) xg, coalesce(s.key_passes,0) kp, coalesce(s.interceptions,0) itc, coalesce(s.recoveries,0) rec, coalesce(s.ground_duels_won,0)+coalesce(s.aerial_duels_won,0) dw, coalesce(s.ground_duels_total,0)+coalesce(s.aerial_duels_total,0) dt, coalesce(s.aerial_duels_won,0) aw, coalesce(s.aerial_duels_total,0) at, coalesce(s.passes_completed,0) pc, coalesce(s.passes_total,0) pt, coalesce(s.progressive_passes,0) pp, coalesce(s.chances_created,0) cc, coalesce(s.tackles_won,0) tw, coalesce(s.tackles_total,0) tt, coalesce(s.gk_saves,0) sv, coalesce(s.gk_shots_faced_on_target,0) sf, (SELECT count(*) FROM match_events e WHERE e.is_demo AND e.match_id=mp.match_id AND e.type='goal' AND e.player_id=mp.player_id) g, (SELECT count(*) FROM match_events e WHERE e.is_demo AND e.match_id=mp.match_id AND e.type='goal' AND e.assisted_by_player_id=mp.player_id) a, (SELECT count(*) FROM match_events e WHERE e.is_demo AND e.match_id=mp.match_id AND e.type='yellow_card' AND e.player_id=mp.player_id) yc, (SELECT count(*) FROM match_events e WHERE e.is_demo AND e.match_id=mp.match_id AND e.type='red_card' AND e.player_id=mp.player_id) rc FROM match_participations mp JOIN matches m ON m.id=mp.match_id JOIN position_catalog pc ON pc.code=mp.detailed_position LEFT JOIN player_match_detailed_stats s ON s.match_id=mp.match_id AND s.player_id=mp.player_id AND s.is_demo WHERE mp.is_demo ORDER BY m.matchday, mp.match_id, mp.player_id) TO STDOUT WITH CSV HEADER \g :participations

-- Statistiques d'équipe par match (pour les forces d'équipe à date)
COPY (SELECT a.team_id, m.matchday, a.is_home, a.goals_scored gf, b.goals_scored ga, a.expected_goals xg, b.expected_goals xga, a.possession_pct poss, a.shots_total sh FROM match_team_stats a JOIN match_team_stats b ON b.match_id=a.match_id AND b.team_id<>a.team_id JOIN matches m ON m.id=a.match_id WHERE a.is_demo ORDER BY m.matchday) TO STDOUT WITH CSV HEADER \g :team_matches

-- Historique des scores « Rôle et apport » (ligne « famille jouée »), daté par journée
COPY (SELECT r.player_id, r.period_end::date, r.position_family_evaluated fam, r.score, r.reliability, (SELECT max(matchday) FROM matches m WHERE m.is_demo AND m.match_date::date <= r.period_end::date) AS md FROM player_role_evaluations r WHERE r.period_end IS NOT NULL AND r.role_fit_score = 0 AND r.role_config_version_id = 1) TO STDOUT WITH CSV HEADER \g :role_history
