#!/usr/bin/env python3
"""Additional reviewed French phrases without accent characters."""
import json
import pathlib
root = pathlib.Path(__file__).resolve().parents[1]
translations = {
"❌ Pas d'association": "❌ No association",
"Date de naissance *": "Date of Birth *",
"Risque de blessure": "Injury Risk",
"Type de licence": "Licence Type",
"Affichage de": "Showing",
"sur": "of",
"⚡ Initialiser les Permissions": "⚡ Initialize Permissions",
"Centre de Notifications": "Notification Center",
"Risque de blessure:": "Injury risk:",
"Note du Match:": "Match rating:",
"Tirs au but": "Shots on Target",
"Score Tirs au but": "Penalty Shootout Score",
"Incidents avec le Public": "Spectator Incidents",
"Historique des Dossiers": "Record History",
"Logo du club": "Club Logo",
"💾 Sauvegarder les modifications": "💾 Save Changes",
"Nom du Patient": "Patient Name",
"📋 Instructions de Test": "📋 Test Instructions",
"Cliquez sur une dent": "Click a tooth",
"Survolez les dents": "Hover over the teeth",
"pour voir l'effet de hover": "to see the hover effect",
"Position des dents :": "Tooth positions:",
"Score de Valeur 8.7/10": "Value Score 8.7/10",
"Score de Valeur": "Value Score",
"Valeur globale du dataset": "Overall dataset value",
"Score Global de Valeur": "Overall Value Score",
"Centre de Performances FIFA Connect": "FIFA Connect Performance Center",
"Analyse des Tendances": "Trend Analysis",
"Pas": "No",
"Plan de traitement:": "Treatment plan:",
"Club de formation:": "Training club:",
"🎯 Voir les logos officiels": "🎯 View Official Logos",
};
translations.update({
"🧪 Tester les composants": "🧪 Test Components",
"Pas de photo": "No photo",
"🏆 Type de Licence": "🏆 Licence Type",
"📷 Photo du Demandeur": "📷 Applicant Photo",
"Afrique du Sud": "South Africa",
"Tables les Plus Volumineuses": "Largest Tables",
"Niveaux de Log (24h)": "Log Levels (24h)",
"📊 Indicateurs de Performance": "📊 Performance Indicators",
"Tableau de bord Administrateur - Med Predictor": "Administrator Dashboard - Med Predictor",
"🏥 Tableau de bord Administrateur": "🏥 Administrator Dashboard",
"Avec Club": "With Club",
"Avec Association": "With Association",
"Contrat jusqu'au": "Contract until",
"Licence en attente de validation": "Licence pending validation",
"Connectez-vous pour voir vos notifications": "Sign in to view your notifications",
"Permissions par module indisponibles": "Module permissions unavailable",
"Cette saison": "This Season",
"Tendances de Performance": "Performance Trends",
"Niveau de forme": "Fitness Level",
"Alertes sur les mesures": "Measurement Alerts",
"Analyse des blessures": "Injury Analysis",
"Alertes de performance actives": "Active Performance Alerts",
"Nom de la permission": "Permission Name",
"Matrice des Permissions par Module": "Module Permission Matrix",
"💾 Sauvegarder les Permissions": "💾 Save Permissions",
"Types de Transferts": "Transfer Types",
"Liste des Transferts": "Transfer List",
"De:": "From:",
"💾 Sauvegarder les Modifications": "💾 Save Changes",
"🗑️ Nettoyer les anciens logs": "🗑️ Clear Old Logs",
"Date de fin": "End Date",
"Nettoyer les anciens logs": "Clear Old Logs",
"Supprimer les logs plus anciens que (jours)": "Delete logs older than (days)",
"ID du Log": "Log ID",
"Types de Contenu": "Content Types",
"Liste des Pages": "Page List",
"Liste des Annonces": "Announcement List",
"📁 Uploader des Fichiers": "📁 Upload Files",
"Liste des Articles": "Article List",
});
translations.update({
"Analyse de la force": "Strength Analysis",
"Simulation des performances": "Performance Simulation",
"🏛️ Associations de Football": "🏛️ Football Associations",
"+ Ajouter une association": "+ Add an Association",
"Logo de l'association": "Association Logo",
"Drapeau du pays": "Country Flag",
"Statut de Validation": "Validation Status",
"Alertes de Fraude": "Fraud Alerts",
"Nom de l'Association *": "Association Name *",
"Administrateur de Ligue": "League Administrator",
"Email de Contact *": "Contact Email *",
"Logo de l'Association": "Association Logo",
"Description de l'Association": "Association Description",
"Analyse en cours avec GPT-4...": "Analysis in progress with GPT-4...",
"Erreur lors de l'analyse GPT-4": "GPT-4 analysis error",
"📱 Portail des Appareils": "📱 Device Portal",
"Nom du club *": "Club Name *",
"Laissez vide pour conserver le logo actuel": "Leave empty to keep the current logo",
"Pour la": "For the",
"ID du titulaire": "Holder ID",
"Recommandations de performance": "Performance Recommendations",
"Rendez-vous du jour": "Today's Appointments",
"🔄 Synchroniser avec FIFA": "🔄 Sync with FIFA",
"Suivi des performances et classements": "Track performance and standings",
"Engagements des Clubs": "Club Entries",
"Statut du club": "Club Status",
"Calendrier des Fixtures": "Fixture Schedule",
"Semaine du 15-21 Septembre 2024": "Week of 15-21 September 2024",
"Notre Club": "Our Club",
"Stade des Sports": "Sports Stadium",
"Vue par Jour": "Daily View",
"Tableau de bord analytique": "Analytics Dashboard",
"Statut de connexion FIFA": "FIFA Connection Status",
"Type de Transaction": "Transaction Type",
"tableau de bord": "dashboard",
"Bilan financier du trimestre": "Quarterly Financial Report",
});
translations.update({
"Connecter des logiciels": "Connect Software",
"Connecter vos comptes bancaires": "Connect Your Bank Accounts",
"Connexion de comptes bancaires": "Bank Account Connection",
"Connectez vos logiciels comptables professionnels": "Connect Your Professional Accounting Software",
"Import automatique des transactions et synchronisation des comptes.": "Automatically import transactions and synchronize accounts.",
"Import de fichiers": "File Import",
"Historique des Synchronisations": "Synchronization History",
"Consulter l'historique des actions et modifications": "View the history of actions and changes",
"📄 Types de Licence": "📄 Licence Types",
"Email de contact": "Contact Email",
"Sans emploi": "Unemployed",
"🌐 Voir Flag Icons sur GitHub": "🌐 View Flag Icons on GitHub",
"URL de l'image": "Image URL",
"Entrez l'URL d'une image externe": "Enter an external image URL",
})

translations.update({
"Logo officiel sur le site": "Official Logo on Website",
"Logos des Clubs FTF - Ligue 1": "FTF Club Logos - Ligue 1",
"🏆 Logos des Clubs FTF": "🏆 FTF Club Logos",
"Logos Originaux des Clubs FTF - Ligue 1": "Original FTF Club Logos - Ligue 1",
"🏆 Logos Originaux des Clubs FTF": "🏆 Original FTF Club Logos",
"🎯 Pourquoi cette page ?": "🎯 Why This Page?",
"• Cette page vous guide vers les sites officiels": "• This page directs you to the official websites",
"🔗 Comment obtenir les vrais logos ?": "🔗 How to Obtain the Real Logos?",
"• Visitez les sites officiels des clubs": "• Visit the clubs' official websites",
"• Contactez directement les clubs pour autorisation": "• Contact the clubs directly for permission",
"• Utilisez les logos fournis par la FTF": "• Use the logos provided by the FTF",
"• Respectez les droits d'utilisation": "• Respect usage rights",
})

en_file = root / 'resources/lang/en.json'
old = en_file.read_text()
known = json.loads(old)
new = {k:v for k,v in translations.items() if k not in known}
if new:
    items = ',\n'.join('  '+json.dumps(k,ensure_ascii=False)+': '+json.dumps(v,ensure_ascii=False) for k,v in new.items())
    pos = old.rfind('}')
    en_file.write_text(old[:pos].rstrip()+',\n'+items+'\n'+old[pos:])
print('Added',len(new),'English translations')
